### PR TITLE
Add the mach_msg_type_descriptor_t structure.

### PR DESCRIPTION
**Pull request by turbocool3r**
Adds the mach_msg_type_descriptor_t structure that represents an untyped descriptor.

Also bumps the version since in my last pull request I've introduced a breaking change by changing a parameter in a public method (mach_msg_ool_descriptor_t::new).

### CODE REVIEW

**Comment by turbocool3r** [comment]
I've fixed mach-test failing due to mach_msg_type_descriptor_t containing bitfields, but it will still fail because of __darwin_arm_thread_state64. Should I fix that in this pull request or create a new one?

**Comment by turbocool3r** [comment]
Seems like this only happens on the latest Xcode so nvm.

**Comment by JohnTitor** [comment]
Please drop 4caf16a1ee1ddc6ef638ec35ada717e42f37d5cd, that should happen when releasing.

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Pull request merged**
